- hosts: pine64
  remote_user: ubuntu  

  tasks:
  - name: Set authorized key took from file
    authorized_key:
      user: ubuntu
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

