- hosts: pine64
  remote_user: ubuntu
  vars:
    username: sup

  vars_prompt:
    - name: password
      prompt: "set new password for newly created user"
    - name: nas_password
      prompt: "what's your nas (samba) password?"

  tasks:
  - name: add group for user
    shell: groupadd -g 501 {{username}}
    become: true

  - name: add user
    shell: useradd -m -d /home/{{username}} -s /bin/bash -u 501 -g 501 {{username}}
    become: true

  - name: set password for user
    shell: 'printf "%s\n" {{password}} {{password}} | passwd {{username}}'
    become: true

  - name: add admin group for sudo purposes
    shell: groupadd admin
    become: true

  - name: add newly created user to admin group
    shell: usermod -a -G admin {{username}}
    become: true

  # TODO temporarily here - it should be moved (despite last task) to separate file. I've put it here to not mess with ssh keys for new user as a shortcut

  - name: update sources list for package manager
    shell: apt update
    become: true

  - name: install locate, vim, screen, htop
    shell: apt -y install locate vim screen htop
    become: true

  # TODO figure out if reboot is needed after resize
  - name: resize rootfs to take use of whole sd card
    shell: /usr/local/sbin/resize_rootfs.sh
    become: true

  - name: install graphical interface
    shell: /usr/local/sbin/install_mate_desktop.sh
    become: true

  - name: install apt-transport-https binutils
    shell: apt -y install apt-transport-https binutils
    become: true

  - name: add dev2day.de key to apt
    shell: wget -O - https://dev2day.de/pms/dev2day-pms.gpg.key | apt-key add -
    become: true

  - name: add dev2day.de repo to apt
    shell: echo "deb [arch=armhf] https://dev2day.de/pms/ jessie main" | tee /etc/apt/sources.list.d/pms.list
    become: true

  - name: add armhf architecture to dpkg
    shell: dpkg --add-architecture armhf
    become: true

  - name: update sources list for package manager
    shell: apt update
    become: true

  - name: install plexmediaserver
    shell: apt -y install plexmediaserver-installer:armhf
    become: true

  - name: restart plexmediaserver service
    shell: service plexmediaserver restart
    become: true

  - name: install mkvtoolnix cifs-utils
    shell: apt -y install mkvtoolnix cifs-utils
    become: true

  # TODO add parameters and ask user for password
  - name: add samba mount to NAS
    shell: echo "//192.168.0.1/Store-Small       /media/Airport-Store-Small      cifs    username={{username}},password={{nas_password}},uid=501,sec=ntlm   0 0" | tee -a /etc/fstab
    become: true

  - name: create directory for samba mount
    shell: mkdir -p /media/Airport-Store-Small
    become: true

  - name: change owner of samba mount
    shell: chown {{username}}:{{username}} /media/Airport-Store-Small
    become: true

  - name: mount samba mount
    shell: mount /media/Airport-Store-Small
    become: true

  # TODO kill processes by ubuntu just in case (i.e. manual loging into console)
  # - name: delete default ubuntu user as it has default password
  #   shell: userdel ubuntu
  #   become: true

# TODO console-setup displays ncurses dialog waits for user submision despite -y ;/
  # - name: upgrade packages
  #   shell: apt -y upgrade
  #   become: true

  # - name: reboot after changes
  #   shell: reboot
  #   become: true
